### ISSUE TITLE
add zend expressive 2 compatible

### ISSUE THREAD

**Issue by Sohorev** [bitExpert/prophiler-psr7-middleware#14]
When I am run:
composer require --dev bitexpert/prophiler-psr7-middleware

error occured:
Installation request for zendframework/zend-stratigility (locked at 2.0.1) -> satisfiable by zendframework/zend-stratigility[2.0.1].

**Comment by shochdoerfer** [comment]
@Sohorev thanks for pointing out. Mind sending a PR to fix the issue?

**Comment by shochdoerfer** [comment]
@Sohorev I just updated the dev-master version to use Stratigility version 2.x. Could you please test if it is working for you?

**Comment by Sohorev** [comment]
Thankyou it is installs and works normall

**Comment by shochdoerfer** [comment]
Will create a new release later today. That way you do not need to depend on a dev-master version.

**Comment by shochdoerfer** [comment]
You can now use the 0.4.0 release of this package instead of dev-master.
