### ISSUE TITLE
Question: how to access Profiler from action middleware

### ISSUE THREAD

**Issue by lowtower** [bitExpert/prophiler-psr7-middleware#22]
Hello Stephan,

maybe a stupid question.
In the README You provide an example for `zend-expressive 2.0` and for configuration:
```php
$profiler->start('\My\Class::doSomeOtherThing', ['additional' => 'information'], 'My Component');
// here be your custom code
$profiler->stop();
```
I want to profile some code in an action middleware, but I don't have the `$profiler` variable mentioned above. Is there a simple way to get the profiler object from within the middleware?
I don't want to add a dependency and change factories for just a short and temporary profiling.
Any suggestions?
Or have I misunderstood something?

Thanks in advance,
LowTower.

**Comment by shochdoerfer** [comment]
$prophiler is an instance of `\Fabfuel\Prophiler\Profiler`, the instance you create in `config/pipeline.php`. Ideally you would need to inject that reference into your action middleware. 

If this is not possible I would suggest that you build a `ProphilerRegistry` and call `ProphilerRegistry::set($prophiler)` in the `config/pipeline.php` and call `ProphilerRegistry::get()` in your action middleware.

**Comment by lowtower** [comment]
Thanks for Your quick reponse!
I did it with injection - it is  just not very comfortable, but okay.
Nevertheless, the debugbar is rendered in general, but my additions are not.
What is wrong?
Any ideas?
Maybe I am just too stupid to understand, I apologize!
Thanks for Your help!

Additionally to Your description, I had to add a factory for the Profiler to the dependencies:
```php
...
            Fabfuel\Prophiler\Profiler::class => InvokableFactory::class,
...
```

config/pipeline.php:
```php
...
$app->pipe(ErrorHandler::class);

// Debug Bars
if ($debug) {
    // Prophiler
    $profiler   = new Fabfuel\Prophiler\Profiler();
    $toolbar    = new Fabfuel\Prophiler\Toolbar($profiler);
    $middleware = new bitExpert\Http\Middleware\Psr7\Prophiler\ProphilerMiddleware($toolbar);
    $app->pipe($middleware);
}

$app->pipe(ServerUrlMiddleware::class);
...
```
ActionMiddleware.php
```php
use Fabfuel\Prophiler\Profiler;
class ActionMiddleware implements ServerMiddlewareInterface
{
    private $profiler;

    public function __construct(
        Profiler $profiler,
        TemplateRendererInterface $template = null
    ) {
        $this->profiler = $profiler;
        $this->template = $template;
    }

    public function process(ServerRequestInterface $request, DelegateInterface $delegate): ResponseInterface
    {
$logger = new \Fabfuel\Prophiler\Adapter\Psr\Log\Logger($this->profiler);
$multiplicator = 10;
$wait = function ($time) use ($multiplicator) {
    return $time * rand(intval($multiplicator * .8), intval($multiplicator * 1.2));
};
$bootstrap = $this->profiler->start('Bootstrap', ['lorem' => 'ipsum'], 'Application');
usleep($wait(50));
$this->profiler->stop($bootstrap);
$logger->info('Bootstrap has finished', ['some' => 'context']);

        $response = new HtmlResponse($this->template->render('action::test'));

        return $response;
    }
}
```

**Comment by lowtower** [comment]
> ..., but my additions are not.

I mean, that the timeline is empty, but i expect the entry 'Bootstrap'.
And I expect an info, that 'Bootstrap has finished'.

**Comment by shochdoerfer** [comment]
The problem in this case might be that you create 2 `Fabfuel\Prophiler\Profiler` - one in the pipeline config and the other one via the ServiceManager. Can you retrieve the one from the ServiceManager in the pipeline config?

**Comment by lowtower** [comment]
Hello Stephan,

Ich changed the pipeline.php, such that the Profiler is retrieved from the container:

    $profiler = $app->getContainer()->get(Fabfuel\Prophiler\Profiler::class);

But nothing changes :-(

**Comment by lowtower** [comment]
Sorry,
my fault!
It works now!
Thanks a lot!

**Comment by shochdoerfer** [comment]
You are welcome. Would appreciate if you would blog about your findings ;)
