### ISSUE TITLE
If no Content-Type is set 

### ISSUE THREAD

**Issue by harikt** [bitExpert/prophiler-psr7-middleware#8]
In the response if content-type is not set the tool bar is not shown.

**Comment by shochdoerfer** [comment]
Not sure if I get it right but do you want to show / render the toolbar when no content type was set or should it not be shown if the content type is not set?

**Comment by harikt** [comment]
@shochdoerfer my intention was to show the toolbar even if there is no content type set.

**Comment by shochdoerfer** [comment]
@harikt but isn`t that problematic? If you forget to declare a content type for your json response it would also render the toolbar and effectively messing up your JSON response. 

Can`t you simply set the content type in your action/controller/whatever? Just want to understand we you are coming from ;)

**Comment by harikt** [comment]
@shochdoerfer for a json I will for sure will set the content type. Yes you can tell adding content type is correct.

I did some debugging to understand where the issue is when I was not seeing the toolbar.

If you feel with out content type feel free to close it :) .

Thank you.

**Comment by shochdoerfer** [comment]
@harikt Thanks for making clear what you want to achieve.

Given your "requirements" I would love to not accept the PR simply to reduce the possibility of errors and bug reports in the future. Even though I am not able to accept the PR please do not feel disappointed and continue contributing to this project in the future. Thanks Hari.

**Comment by harikt** [comment]
no issues at all :) .
